// Mocks generated by Mockito 5.4.6 from annotations
// in investment_tracker/test/features/auth/domain/usecases/register_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:investment_tracker/features/auth/domain/entities/auth_response_entity.dart'
    as _i3;
import 'package:investment_tracker/features/auth/domain/entities/session_entity.dart'
    as _i8;
import 'package:investment_tracker/features/auth/domain/entities/two_factor_entity.dart'
    as _i4;
import 'package:investment_tracker/features/auth/domain/entities/user_entity.dart'
    as _i2;
import 'package:investment_tracker/features/auth/domain/repositories/auth_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponseEntity_1 extends _i1.SmartFake
    implements _i3.AuthResponseEntity {
  _FakeAuthResponseEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTwoFactorEntity_2 extends _i1.SmartFake
    implements _i4.TwoFactorEntity {
  _FakeTwoFactorEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserEntity> register({
    required String? email,
    required String? username,
    required String? password,
    String? fullName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
              #fullName: fullName,
            }),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #username: username,
                  #password: password,
                  #fullName: fullName,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i3.AuthResponseEntity> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i6.Future<_i3.AuthResponseEntity>.value(
              _FakeAuthResponseEntity_1(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponseEntity>);

  @override
  _i6.Future<_i3.AuthResponseEntity> login2FA({
    required String? email,
    required String? password,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login2FA, [], {
              #email: email,
              #password: password,
              #code: code,
            }),
            returnValue: _i6.Future<_i3.AuthResponseEntity>.value(
              _FakeAuthResponseEntity_1(
                this,
                Invocation.method(#login2FA, [], {
                  #email: email,
                  #password: password,
                  #code: code,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResponseEntity>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> resendVerificationEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> verifyEmail({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#email: email, #code: code}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetPassword({
    required String? email,
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.TwoFactorEntity> setup2FA() =>
      (super.noSuchMethod(
            Invocation.method(#setup2FA, []),
            returnValue: _i6.Future<_i4.TwoFactorEntity>.value(
              _FakeTwoFactorEntity_2(this, Invocation.method(#setup2FA, [])),
            ),
          )
          as _i6.Future<_i4.TwoFactorEntity>);

  @override
  _i6.Future<void> enable2FA(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#enable2FA, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disable2FA(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#disable2FA, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.SessionEntity>> getSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, []),
            returnValue: _i6.Future<List<_i8.SessionEntity>>.value(
              <_i8.SessionEntity>[],
            ),
          )
          as _i6.Future<List<_i8.SessionEntity>>);

  @override
  _i6.Future<void> revokeSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeSession, [sessionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> revokeAllOtherSessions() =>
      (super.noSuchMethod(
            Invocation.method(#revokeAllOtherSessions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.UserEntity> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<_i2.UserEntity> updateProfile({
    String? fullName,
    String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #username: username,
            }),
            returnValue: _i6.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(
                this,
                Invocation.method(#updateProfile, [], {
                  #fullName: fullName,
                  #username: username,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserEntity>);

  @override
  _i6.Future<void> deleteAccount(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [password]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getStoredUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredUserId, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> clearLocalAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalAuthData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
